apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "leasecontroller.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "leasecontroller.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "leasecontroller.fullname" . }}-serviceaccount
  namespace: {{ .Release.Namespace }}
