apiVersion: v1
kind: Service
metadata:
  name: {{ include "leasecontroller.fullname" . }}-health
  labels:
    {{- include "leasecontroller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "leasecontroller.selectorLabels" . | nindent 4 }}
