apiVersion: v1
kind: Service
metadata:
  name: {{ include "leasecontroller.fullname" . }}-metrics
  labels:
    {{- include "leasecontroller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "leasecontroller.selectorLabels" . | nindent 4 }}
