coverage:
  status:
    project:
      default:
        # Do not fail on coverage drop or threshold
        enabled: true
        target: auto
        threshold: 0%
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: success
    patch:
      default:
        enabled: true
        target: auto
        threshold: 0%
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: success
