# This rule is not used by the project object-lease-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the object-lease-controller.ullberg.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: object-lease-operator
    app.kubernetes.io/managed-by: kustomize
  name: leasecontroller-editor-role
rules:
- apiGroups:
  - object-lease-controller.ullberg.io
  resources:
  - leasecontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - object-lease-controller.ullberg.io
  resources:
  - leasecontrollers/status
  verbs:
  - get
