apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "object-lease-controller.ullberg.us/v1alpha1",
          "kind": "LeaseController",
          "metadata": {
            "name": "leasecontroller-sample"
          },
          "spec": {
            "leasecontroller": {
              "group": "apps",
              "kind": "Deployment",
              "version": "v1"
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: Networking
    certified: "false"
    containerImage: ghcr.io/ullbergm/object-lease-operator:latest
    createdAt: "2025-07-21T21:08:08Z"
    description: Operator to manage object leases in Kubernetes.
    operators.operatorframework.io/builder: operator-sdk-v1.41.1
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
    repository: https://github.com/ullbergm/object-lease-controller
    support: Magnus Ullberg <magnus@ullberg.us>
  name: object-lease-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: LeaseController
      name: leasecontrollers.object-lease-controller.ullberg.us
      version: v1alpha1
  description: |
    ## Introduction
    This Operator manages object leases in Kubernetes.
    ## Object Lease Management
    The Object Lease Operator integrates with Kubernetes to manage the lifecycle of object leases, ensuring that resources are properly allocated and released as needed.
  displayName: Object Lease Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - object-lease-controller.ullberg.us
          resources:
          - leasecontrollers
          - leasecontrollers/status
          - leasecontrollers/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          - services
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - '*'
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: object-lease-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: object-lease-operator
          control-plane: controller-manager
        name: object-lease-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: object-lease-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                app.kubernetes.io/name: object-lease-operator
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-require-rbac
                - --metrics-secure
                - --metrics-bind-address=:8443
                - --leader-elect
                - --leader-election-id=object-lease-operator
                - --health-probe-bind-address=:8081
                image: ghcr.io/ullbergm/object-lease-operator:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: object-lease-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: object-lease-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Lease
  - TTL
  - controller
  links:
  - name: Github Repo
    url: https://github.com/ullbergm/object-lease-controller
  maintainers:
  - email: magnus@ullberg.us
    name: Magnus Ullberg
  maturity: beta
  minKubeVersion: 1.13.0
  provider:
    name: Magnus Ullberg
  version: 0.0.1
