---
name: PR - Labeler

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: labeler

jobs:
  labeler:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: 🏷️ Apply labels
        uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7
        with:
          configuration-path: .github/labeler.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
